# Generated by Django 4.1 on 2023-10-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_userprofileinfo_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='user',
        ),
    ]
