# Generated by Django 4.1 on 2023-10-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_userprofile_delete_userprofileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='profile_pics/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
