# Generated by Django 4.1 on 2023-10-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_uploadedimage_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='title',
            new_name='username',
        ),
    ]
