# Generated by Django 4.1 on 2023-10-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_rename_title_uploadedimage_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ImageField(upload_to='profile_pics')),
                ('imagePassport', models.ImageField(upload_to='profile_pics')),
            ],
        ),
    ]
