# Generated by Django 4.1 on 2023-10-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_uploadkyc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='username',
            new_name='title',
        ),
    ]
