# Generated by Django 4.1 on 2023-10-16 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_rename_username_uploadedimage_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='title',
            new_name='username',
        ),
    ]
