# Generated by Django 4.1 on 2023-10-19 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0012_accountbalance_totalactiveplan_totalbonus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotalActivePlan',
            new_name='TotalActiveInvestmentPlan',
        ),
    ]
