# Generated by Django 4.1 on 2023-10-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0013_rename_totalactiveplan_totalactiveinvestmentplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='content',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totalactiveinvestmentplan',
            name='content',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totalbonus',
            name='content',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totaldeposit',
            name='content',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totalinvestmentplan',
            name='content',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totalprofit',
            name='content',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totalreferralbonus',
            name='content',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totalwithdrawals',
            name='content',
            field=models.IntegerField(),
        ),
    ]
