# Generated by Django 4.1 on 2023-10-20 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0014_alter_accountbalance_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBalance',
        ),
        migrations.DeleteModel(
            name='TotalActiveInvestmentPlan',
        ),
        migrations.DeleteModel(
            name='TotalBonus',
        ),
        migrations.DeleteModel(
            name='TotalDeposit',
        ),
        migrations.DeleteModel(
            name='TotalInvestmentPlan',
        ),
        migrations.DeleteModel(
            name='TotalProfit',
        ),
        migrations.DeleteModel(
            name='TotalReferralBonus',
        ),
        migrations.DeleteModel(
            name='TotalWithdrawals',
        ),
    ]
