# Generated by Django 4.1 on 2023-10-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0018_alter_dashboarduser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='amount',
            field=models.IntegerField(default=10),
        ),
    ]
