# Generated by Django 4.1 on 2023-10-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0019_dashboarduser_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DashBoardUser',
        ),
    ]
