# Generated by Django 5.0 on 2023-12-15 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0020_delete_dashboarduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_balance', models.FloatField()),
                ('deposit_profit', models.FloatField()),
                ('total_investment', models.FloatField()),
                ('total_active', models.FloatField()),
                ('total_deposit', models.FloatField()),
                ('total_withdraw', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
