# Generated by Django 5.0 on 2023-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0021_accountbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='acc_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='deposit_profit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='total_active',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='total_investment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='total_withdraw',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
