# Generated by Django 5.0 on 2023-12-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0024_accountbalance_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='referral',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
