# Generated by Django 5.0 on 2023-12-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0026_accountbalance_pr_amount1_accountbalance_pr_amount10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='tr_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='tr_withdraw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
