# Generated by Django 5.0 on 2023-12-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0027_accountbalance_tr_deposit_accountbalance_tr_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='pr_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
