# Generated by Django 5.0 on 2023-12-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0035_alter_accountbalance_pr_plan1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount1',
            new_name='tr_amt1',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount10',
            new_name='tr_amt10',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount11',
            new_name='tr_amt11',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount12',
            new_name='tr_amt12',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount2',
            new_name='tr_amt2',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount3',
            new_name='tr_amt3',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount4',
            new_name='tr_amt4',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount5',
            new_name='tr_amt5',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount6',
            new_name='tr_amt6',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount7',
            new_name='tr_amt7',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount8',
            new_name='tr_amt8',
        ),
        migrations.RenameField(
            model_name='accountbalance',
            old_name='tr_amount9',
            new_name='tr_amt9',
        ),
    ]
