# Generated by Django 5.0 on 2023-12-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0036_rename_tr_amount1_accountbalance_tr_amt1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt1',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt10',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt11',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt12',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt2',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt3',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt4',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt5',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt6',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt7',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt8',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='tr_amt9',
        ),
    ]
