# Generated by Django 5.0 on 2023-12-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0038_accountbalance_t_amount1_accountbalance_t_amount10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
