# Generated by Django 5.0 on 2023-12-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0040_alter_accountbalance_t_amount1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='t_amount1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
