# Generated by Django 5.0 on 2023-12-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0045_accountbalance_tr_amount1_accountbalance_tr_amount10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode1',
            field=models.CharField(blank=True, default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode2',
            field=models.CharField(blank=True, default='2', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode3',
            field=models.CharField(blank=True, default='3', max_length=20),
        ),
    ]
