# Generated by Django 5.0 on 2023-12-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0046_alter_accountbalance_tr_paymentmode1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='tr_paymentmode9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
