# Generated by Django 5.0 on 2023-12-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0049_alter_accountbalance_tr_date1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type1',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type10',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type11',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type12',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type2',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type3',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type4',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type5',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type6',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type7',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type8',
        ),
        migrations.RemoveField(
            model_name='accountbalance',
            name='pr_type9',
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountbalance',
            name='pr_profit9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_amount9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_date9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan1',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan10',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan11',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan12',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan3',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan4',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan5',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan6',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan7',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan8',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountbalance',
            name='pr_plan9',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
